default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: text_to_email_development

production:
  <<: *default
  database: text_to_email_production
  username: brant
  password: